### ISSUE TITLE
This Repo is actually Epic?!?!

### ISSUE THREAD

**Issue by BergEB** [WrightZAW/portfolio#1]
Great job buddy! This fr*cking cr*p is sick!
I guess I was right, _**ADDY REALLY DOES GO HARD!**_

hugs and kisses,
Me! Eronk!

**Comment by WrightZAW** [comment]
Wow Erik!
Thank you so much for your insightful message!!!! 👍 
Hope to hear from you soon :)

hugs and kisses,
Big Z <3
